# Generated by Django 4.2.6 on 2023-10-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_follow_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='starting_date',
            new_name='date',
        ),
    ]
