# Generated by Django 4.2.6 on 2023-11-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_user_token_user_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verify',
            new_name='is_verified',
        ),
    ]
