# Generated by Django 4.2.6 on 2023-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_verify_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, to='user_profile.follow'),
        ),
    ]
